(defun force ()
  "initialize force development workflow"
  (interactive)
  (defvar *-project-name "force")
  (defvar force-server t)
  (defvar force-root-dir "/Volumes/Main/Users/akatovda/Documents/Stuff/force")
  (setenv "DATABASE_URL" "postgres://akatovda:qwadzv@localhost:5432/force")
  (venv-workon *-project-name)
  (dz-defservice force-server "python"
                 :args ("manage.py" "runserver")
                 :cd force-root-dir)
  (elscreen-create)
  (force-server-start)
  (delete-other-windows)
  (spawn-shell (concatenate 'string "*" *-project-name "-shell*") force-root-dir)
  (find-file (concatenate 'string force-root-dir "/" *-project-name ".el"))
  (find-file (concatenate 'string force-root-dir "/" *-project-name ".org"))
  (delete-other-windows))

(provide 'force)
