СИЗО -- с тобой до конца!

Параша справа внизу, а выше рейтинг заказывающих чуваков.
Параша -- колонка.
Петух -- подумать над званием.

Ачивки: качер, диетолог, штрудель
Ачивка за получение всех ачивок!

https://github.com/kadirahq/react-storybook


* TODO Categories must have hash
* Menu designs
http://www.creativebloq.com/design/creative-menu-designs-1131620
** Вёрстку таблицы взять отсюда: http://elemental-ui.com/css
** Или отсюда: http://www.material-ui.com/#/components/table
** Fuzzy-поиск отсюда: http://www.material-ui.com/#/components/auto-complete
** Бейджи тоже отсюда: http://www.material-ui.com/#/components/badge
** Поповеры отсюда: http://www.material-ui.com/#/components/popover
* Deploy
** heroku config:add BUILDPACK_URL=git://github.com/jiaaro/heroku-buildpack-django.git
* Features
** Цитаты: в тюрьме сейчас ужин, макороны.
- украл, выпил, в тюрьму!
- Дмитрий Андреевич, тут такое дело...
- Дмитрий Андреевич, мы вот по какому вопросу...
- Дмитрий Андреевич, у нас на вас кое-что есть...
- Дмитрий Андреевич, люди разное говорят...
- Что ты тут ищешь?
** [[http://react-components.com/component/react-socials][react-socials]]
** [[http://react-components.com/component/react-native-local-auth][react-native-local-auth]]
** from https://khan.github.io/react-components/#button-group:
- tooltip/info-tip
** TODO Override user model
- https://docs.djangoproject.com/en/1.9/topics/auth/customizing/
** DONE product hash
CLOSED: [2016-03-22 Tue 23:06]
- State "DONE"       from "STARTED"    [2016-03-22 Tue 23:06]
CLOCK: [2016-03-22 Tue 22:25]--[2016-03-22 Tue 23:06] =>  0:41
** TODO product history
** TODO Verbose output on force fetch
** TODO force menu cleanup, force menu fetch --from hlebsol
** TODO force menu list-providers
* w3p config
http://localhost:8000/?schema=N4IgLglmA2CmIC4QGED2A7AZhA5iANOAJ4AO8SqARgFawDGYBIJATqmS5LAM6KgCGDCBl4JQYUuRD8WLfkSaZULALb9GSMP0pwmkGFICCQkUwCu6CAEczsAJJhYK0WBa3CUJ6PGTEIKrQMelC6SMaQGEys7LCcEDx8xGSJEslI3K4Q6HiEsOhmKogA2iAAJqgA7ujQqPylTHTQEHQA1orlVTV1UTLc8IRqYHQAFkwZyvAAuoSlsJj8ZtAazL3wAL6E6Pwq5D5pIBksWXgb4DI4sBp7UofHIKfcZjT0V0k3mdn3hABuENwQOl2bz8lFQqDg/HQimUgz8I3oLVBAA97mtTrN5osNEVrn4OtVavVNtspBVYJQSPwLmMnoFlsMwGASAgAPQs+jDVAAOmcLS5bhZ6FgFW4LIAjAA2ADMAFYACwAdgAHABaDnchkqaBMX7/QGIVy2NaTNFrIAA&value=N4IghgxgLglg9gOwM4gFwG1RQJ4AcCmaIAZgCZwDuCANnGKSADQgJgC2hqIF+ARrmADmhZlDAAnYVCJMQSAK68AVvmhEAFlCi5UAel3rqfALRI41AHS8YAL1kA3GEhi8jaYmGpJ8AX0ZY8ThABcW9ZVg4iamjZMUl8aS4efiEROUUVNS4LDgR5AEkofDYAIRhBAAIoUgqwdHVxfGIAXQcnFzdUKHF5X2afIAAA==&object_layout=grid&theme=bootstrap2&disable_collapse&disable_properties&disable_edit_json
* Providers
** http://lunch-time.ru/menu/print-current
** http://netgoloda.ru/zakazat-obed.html?date=22-01-2016
** http://www.obed-v-ofis.ru/menu-goryachie-obedy.php
* Раскрутка
** Офисы
** Отели
