# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mfs', models.CharField(blank=True, max_length=1024)),
                ('tags', models.CharField(blank=True, max_length=1024)),
                ('urls', models.CharField(blank=True, max_length=1024)),
                ('emails', models.CharField(blank=True, max_length=1024)),
                ('phones', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
