# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_wc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='emails',
            field=models.TextField(verbose_name='emails'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phones',
            field=models.TextField(verbose_name='phone numbers'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='tags',
            field=models.TextField(verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='urls',
            field=models.TextField(verbose_name='urls'),
        ),
    ]
