# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
