# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20160625_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='menufile',
            field=models.FileField(default=1, max_length=1024, upload_to='restaurant.MenuFile/bytes/filename/mimetime'),
            preserve_default=False,
        ),
    ]
