# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20160715_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='menufile',
            field=models.FileField(max_length=1024, upload_to='restaurant.MenuFile/bytes/filename/mimetype'),
        ),
    ]
