# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
