# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 13, 0, 29, 41, 254365, tzinfo=utc), verbose_name='added'),
            preserve_default=False,
        ),
    ]
