# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_product_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hash',
            field=models.CharField(default=datetime.datetime(2016, 3, 22, 20, 2, 0, 753913, tzinfo=utc), max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([]),
        ),
    ]
