# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20160322_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
