# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20160322_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
