# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20160327_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True),
        ),
    ]
