# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20160403_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
